MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "mobilenet_v2_detectron2.pth"
  BACKBONE:
    NAME: "build_fcos_mobilenetv2_fpn_backbone"
    FREEZE_AT: 0
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    OUT_CHANNELS: 128
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    POST_NMS_TOPK_TEST: 50
    NUM_CLS_CONVS: 2
    NUM_BOX_CONVS: 2
    NUM_CLASSES: 1
    CLASS_FILTER: [0]
  MASK_ON: True
  MASKIOU_ON: False
  ROI_HEADS:
    NAME: "CenterROIHeads"
    IN_FEATURES: ["p3", "p4", "p5"]
    NUM_CLASSES: 1
    CLASS_FILTER: [0]
  ROI_MASK_HEAD:
    NAME: "SpatialAttentionMaskHead"
    ASSIGN_CRITERION: "ratio"
    NUM_CONV: 2
    CONV_DIM: 128
  ROI_MASKIOU_HEAD:
    NUM_CONV: 2
    CONV_DIM: 128
DATASETS:
  TRAIN: ("coco_2017_val",)
  TEST: ("coco_2017_val",)
SOLVER:
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 4
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (300000, 340000)
  MAX_ITER: 360000
INPUT:
  MIN_SIZE_TRAIN: (580, 600)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
OUTPUT_DIR: "output/centermask/CenterMask-Lite-MNv2-ms-4x"
