MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "mobilenet_v2_detectron2.pth"
  BACKBONE:
    NAME: "build_fcos_mobilenetv2_fpn_backbone"
    FREEZE_AT: 0
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 128
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    IN_FEATURES: ["p3", "p4", "p5"]
    FPN_STRIDES: [8, 16, 32]
    SIZES_OF_INTEREST: [64, 128]
    POST_NMS_TOPK_TEST: 50
    NUM_CLS_CONVS: 2
    NUM_BOX_CONVS: 2
    NUM_CLASSES: 1
    TOP_LEVELS: 0
    CLASS_FILTER: [0]
  MASK_ON: True
  MASKIOU_ON: False
  GLOBALSEG_ON: False
  ROI_HEADS:
    NAME: "CenterROIHeads"
    IN_FEATURES: ["p2", "p3", "p4"]
    NUM_CLASSES: 1
    CLASS_FILTER: [0]
  ROI_MASK_HEAD:
    NAME: "SpatialAttentionMaskHead"
    ASSIGN_CRITERION: "ratio"
    NUM_CONV: 2
    CONV_DIM: 128
    POOLER_RESOLUTION: 16
  ROI_MASKIOU_HEAD:
    NUM_CONV: 2
    CONV_DIM: 128
DATASETS:
  TRAIN: ("cihp",)
  TEST: ("coco_2017_val",)
SOLVER:
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (300000, 340000)
  MAX_ITER: 360000
INPUT:
  MASK_FORMAT: bitmask
  MIN_SIZE_TRAIN: (128,)
  MAX_SIZE_TRAIN: 256
  MIN_SIZE_TEST: 128
  MAX_SIZE_TEST: 256
OUTPUT_DIR: "output/centermask/PersonMask-Lite-MNv2-SEG-ms-2x"
